apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# Install cert-manager CRDs and controller
# In production, install via:
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.0/cert-manager.yaml
#
# This file contains custom configuration for AEGIS
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email for urgent renewal and security notices
    email: admin@aegis-network.io

    # Secret to store ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-account-key

    # HTTP-01 challenge solver
    solvers:
    - http01:
        ingress:
          class: nginx
      selector:
        dnsNames:
        - "*.aegis-edge.io"

    # DNS-01 challenge solver for wildcard certificates
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
        - "aegis-network.io"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: admin@aegis-network.io
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aegis-tls
  namespace: aegis
spec:
  # Secret name where certificate will be stored
  secretName: aegis-tls-secret

  # Certificate duration and renewal
  duration: 2160h  # 90 days
  renewBefore: 720h  # Renew 30 days before expiration

  # Common name and SANs
  commonName: edge.aegis-network.io
  dnsNames:
  - edge.aegis-network.io
  - "*.edge.aegis-network.io"
  - api.aegis-network.io

  # Issuer reference
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io

  # Private key configuration
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always

  # ACME challenge configuration
  usages:
  - digital signature
  - key encipherment
  - server auth
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: "REPLACE_WITH_ACTUAL_CLOUDFLARE_API_TOKEN"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cert-manager
---
# Certificate renewal monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  selector:
    matchLabels:
      app: cert-manager
  endpoints:
  - port: tcp-prometheus-servicemonitor
    interval: 30s
