apiVersion: v1
kind: Namespace
metadata:
  name: aegis
  labels:
    name: aegis
    app.kubernetes.io/name: aegis-edge-node
    app.kubernetes.io/component: infrastructure
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aegis-quota
  namespace: aegis
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: aegis-limits
  namespace: aegis
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: "100m"
      memory: 128Mi
    default:
      cpu: "1"
      memory: 1Gi
    defaultRequest:
      cpu: "500m"
      memory: 512Mi
    type: Container
