apiVersion: v1
kind: ConfigMap
metadata:
  name: river-config
  namespace: aegis
data:
  config.toml: |
    # AEGIS River Proxy Configuration

    http_addr = "0.0.0.0:80"
    https_addr = "0.0.0.0:443"
    origin = "http://origin-backend:8080"

    cache_enabled = true
    cache_addr = "dragonfly:6379"
    cache_ttl_secs = 3600

    log_requests = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: river-proxy
  namespace: aegis
  labels:
    app: river-proxy
    component: edge-proxy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: river-proxy
  template:
    metadata:
      labels:
        app: river-proxy
        component: edge-proxy
    spec:
      containers:
      - name: river-proxy
        image: aegis/river-proxy:latest  # Build and push your image
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: metrics
          containerPort: 9090
          protocol: TCP
        env:
        - name: RUST_LOG
          value: "info"
        - name: CONFIG_PATH
          value: "/etc/river/config.toml"
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /etc/river
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: river-config
---
apiVersion: v1
kind: Service
metadata:
  name: river-proxy
  namespace: aegis
  labels:
    app: river-proxy
    component: edge-proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local  # Preserve source IP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: river-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: river-metrics
  namespace: aegis
  labels:
    app: river-proxy
    component: edge-proxy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
  selector:
    app: river-proxy
