apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m0s
  timeout: 5m0s
  sourceRef:
    kind: GitRepository
    name: aegis-repo-ops
  path: ./ops/k3s
  prune: true
  wait: true
  force: false
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: dragonfly
      namespace: aegis
    - apiVersion: v1
      kind: Service
      name: dragonfly
      namespace: aegis
  patches:
    # Example: Override resource limits for specific environments
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: dragonfly
          namespace: aegis
        spec:
          replicas: 1
      target:
        kind: Deployment
        name: dragonfly
